services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8082:80"
    volumes:
      - C:/Users/nacho/OneDrive/Documentos/Github/LP2:/var/www/html:cached
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nacho
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: nacho
      PMA_PASSWORD: 1234
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
